#!/bin/bash

printf "Running tests:\n\n"

./scripts/lint
lintResult=$?

printf "Running tap tests:\n\n"
tap tests/**/*.js -Rspec --coverage
tapResult=$?

echo "Finished tests."

! (( $tapResult | $lintResult ))
